# Generated by Django 4.2 on 2023-05-04 00:03

from django.db import migrations, models

import peridash.gen_utils


class Migration(migrations.Migration):
    dependencies = [
        ("ticker", "0006_alter_tickersettings_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticker",
            name="id",
            field=models.CharField(
                default=peridash.gen_utils.get_token,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="tickersettings",
            name="id",
            field=models.CharField(
                default=peridash.gen_utils.get_token,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
