# Generated by Django 4.2 on 2023-05-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticker", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="symbol",
            name="is_trending",
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="name",
        ),
        migrations.AddField(
            model_name="symbol",
            name="exchange",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="symbol",
            name="symbol",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
    ]
