# Generated by Django 4.2.1 on 2023-06-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticker", "0008_alter_ticker_symbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticker",
            name="buy",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="ticker",
            name="gain",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="ticker",
            name="loss",
            field=models.FloatField(default=0.0),
        ),
    ]
