version: '3.8'

services:
  db:
    image: postgres:15.2
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build: ./backend
    command: sh -c "pdm run python manage.py migrate && pdm run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/user:/app/user
      - ./backend/core:/app/core
      - ./backend/ticker:/app/ticker
      - ./backend/peridash:/app/peridash
      - ./backend/caltodo:/app/caltodo
      - ./backend/pyproject.toml:/app/pyproject.toml
      - ./backend/pdm.lock:/app/pdm.lock
    ports:
      - "8000:8000"
    depends_on:
      - db
      - memcached
    environment:
      - DB_NAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOSTNAME
      - POSTGRES_PORT
      - TWELVE_DATA_API_KEY
      - CACHE_HOSTNAME
      - CACHE_PORT
  memcached:
    image: memcached:1.6.19-bullseye
    command: memcached -m 128

  # frontend:
  #   build: ./frontend
  #   command: sh -c "npm install && npm start"
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

volumes:
  postgres_data:
