version: '3.8'

services:
  db:
    image: postgres:15.2
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build: ./backend
    volumes:
      - ./backend/user:/app/user
      - ./backend/ticker:/app/ticker
      - ./backend/peridash:/app/peridash
      - ./backend/pyproject.toml:/app/pyproject.toml
      - ./backend/pdm.lock:/app/pdm.lock
      - ./backend/coverage:/app/htmlcov
    ports:
      - "8000:8000"
    depends_on:
      - db
      - memcached
    environment:
      - RUN_ENV
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOSTNAME
      - POSTGRES_PORT
      - TWELVE_DATA_API_KEY
      - CACHE_HOSTNAME
      - CACHE_PORT
      - DJANGO_DEBUG
  memcached:
    image: memcached:1.6.19-bullseye
    command: memcached -m 128

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/coverage:/app/coverage
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL
      - RUN_ENV
volumes:
  postgres_data:
