resources:
- ../base
namespace: dev-peridash
images:
  - name: backend_image
    newName: uintuser/peridash-backend
    newTag: dev
  - name: frontend_image
    newName: uintuser/peridash-frontend
    newTag: dev

configMapGenerator:
- name: backend-env
  envs:
  - ./envs/BACKEND.env

- name: frontend-env
  envs:
  - ./envs/NEXT.env
- name: db-env
  envs:
  - ./envs/POSTGRES.env

patches:
- target:
    version: v1
    kind: Ingress
    name: ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: dev.peridash.com
    - op: replace
      path: /spec/rules/1/host
      value: api.dev.peridash.com
    - op: replace
      path: /spec/tls/0/hosts/0
      value: dev.peridash.com
    - op: replace
      path: /spec/tls/0/hosts/1
      value: api.dev.peridash.com