apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-ci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-account-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments","pods","services","ingresses","configmaps","persistentvolumeclaims"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-account-rolebinding
subjects:
- kind: ServiceAccount
  name: service-ci
roleRef:
  kind: Role
  name: service-account-role
  apiGroup: rbac.authorization.k8s.io
