apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-ci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rollout-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollout-rolebinding
subjects:
- kind: ServiceAccount
  name: gitlab-ci
roleRef:
  kind: Role
  name: rollout-role
  apiGroup: rbac.authorization.k8s.io
