---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: dev-peridash
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: linode-block-storage-retain

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: dev-peridash

spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:15.2
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db-env
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data