name: Backend CI

on:
  push:
    paths:
      - "backend/**"
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build Docker Compose
        run: docker compose build

      - name: Run Docker Compose
        run: |
          docker-compose up -d
          sleep 5
          docker-compose down

      - name: Lint with flake8
        run: docker compose run backend pdm lint

      - name: Run tests
        run: docker compose run backend pdm test

      - name: Stop and remove containers
        if: always()
        run: docker compose down
